const messageActionTypes = {
  GET_MESSAGE: "GET_MESSAGE",
  JOIN_USERS: "JOIN_USERS",
  SET_SEARCH_RESULTS: "SET_SEARCH_RESULTS",
  SET_SEARCH_THERM: "SET_SEARCH_THERM",
  STAR_COUNT_START: "STAR_COUNT_START",
  STAR_COUNT_SUCCESS: "STAR_COUNT_SUCCESS",
  STAR_COUNT_FAILURE: "STAR_COUNT_FAILURE"
};

export default messageActionTypes;
