const channelActionTypes = {
  GET_CHANNELS: "GET_CHANNELS",
  SET_CURRENT_CHANNEL: "SET_CURRENT_CHANNEL",
  SET_FIRST_CHANNEL: "SET_FIRST_CHANNEL",
  FETCH_CHANNELS_START: "FETCH_CHANNELS_START",
  FETCH_CHANNELS_SUCCESS: "FETCH_CHANNELS_SUCCESS",
  FETCH_CHANNELS_FAILURE: "FETCH_CHANNELS_FAILURE",
  SORT_CHANNEL: "SORT_CHANNEL"
};

export default channelActionTypes;
